### ISSUE TITLE
Non-tweets in provided tweets.txt

### ISSUE THREAD

**Issue by mollstacks** [InsightDataScience/coding-challenge#4]
In the given 'tweets.txt' test file, I noticed there were over 700 lines that weren't tweets. They looked something like this:

```
{"limit":{"track":6,"timestamp_ms":"1446218985909"}}
```

In the description, it said that 'tweets.txt' would contain only tweets, and one per line. I just wanted to give you a heads-up.

I'm going to continue to program with the assumption stated in the readme.

**Comment by ddrum001** [comment]
This is an artifact of the real-world Twitter API, which provides messages regarding the rate-limits.  You may ignore these messages since our testing suite will not contain these.
